# Navigation Links
# Fund Route F for Fishkill Campaign

main:
  - name: Home
    url: /#top
    weight: 10
  - name: The Problem
    url: /#problem
    weight: 20
  - name: The Solution
    url: /#solution
    weight: 30
  - name: Why It Works
    url: /#facts
    weight: 40
  - name: Resources
    url: /#resources
    weight: 50
  - name: Take Action
    url: /#take-action
    weight: 60
